
GET http://localhost:3001/api/persons
###
DELETE http://localhost:3001/api/persons/6
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ada Lovelacesss",
  "number": "044-524345",
  "id": "1"
}
###
GET http://localhost:3001/api/persons
